### ISSUE TITLE
It doesn't work return response.json()

### ISSUE THREAD

**Issue by omidgharib** [mdn/fetch-examples#14]
https://github.com/mdn/fetch-examples/blob/febae5dee9144c38cdc680c9c6baa8aec09a4793/fetch-json/index.html#L30

**Comment by chrisdavidmills** [comment]
The example works for me. What browser are you using? What error are you seeing?

**Comment by aidswidjaja** [comment]
fetch-json needs to be run through a web server- it will not work running locally

**Comment by schalkneethling** [comment]
Hey @omidgharib! Thank you for opening this issue. We are combining some of our repositories to enable us to triage pull requests and issues more effectively. Therefore, this specific repository will be merged into the more prominent [dom-examples](https://github.com/mdn/dom-examples) repository. Please open a new issue if you still feel that this issue is relevant. Thank you.
